import assert from 'node:assert/strict';
import test from 'node:test';
import {createRequire} from 'node:module';
import {readFile} from 'node:fs/promises';
import {splitStorageState} from '../lib/storageV2Codec.ts';
import {buildStorageMutation,parseStorageSnapshot} from './storageV2Repository.ts';

const driver=process.env.STORAGE_TEST_PG_MODULE;
test('real PostgreSQL: lossless migration, 24 independent writers, atomic money, receipts, maintenance and immutable history',{skip:!driver},async()=>{
 const {Client}=createRequire(import.meta.url)(driver);
 const server={host:process.env.STORAGE_TEST_PG_HOST??'127.0.0.1',port:Number(process.env.STORAGE_TEST_PG_PORT??55439),user:process.env.STORAGE_TEST_PG_USER??'postgres',password:process.env.STORAGE_TEST_PG_PASSWORD??'local-fixture-only'};
 const database=`storage_core_fixture_${process.pid}_${Date.now()}`;
 const admin=new Client({...server,database:'postgres'});await admin.connect();
 await admin.query(`create database ${database}`);
 const connections=[];
 const connect=async()=>{const client=new Client({...server,database});await client.connect();connections.push(client);return client;};
 try {
  const db=await connect();
  for(const file of ['app_settings.sql','classword.sql','library_competition.sql','storage_v2.sql'])await db.query(await readFile(new URL(`../../supabase/${file}`,import.meta.url),'utf8'));
  const historical={id:'recovered-six',studentNumber:17,delta:6,before:328,after:334,reason:'weekly_mission',createdAt:'2026-09-08T00:00:00.000Z',unrecognized:{preserved:true}};
  const source={version:1,currencyBalances:Object.fromEntries(Array.from({length:23},(_,i)=>[String(i+1),100])),currencyHistory:Object.fromEntries(Array.from({length:23},(_,i)=>[String(i+1),i===16?[historical]:[]])),studentLife:{letters:[],books:[],opaque:{x:null}},studentEconomy:{'1':{inventory:[]}},auctionBids:{},unknown:[3,1,3]};
  await db.query("insert into app_settings(id,value,updated_at) values('school-timer-main',$1,'2026-09-08T00:00:00Z')",[source]);
  await db.query('select storage_set_maintenance(true)');
  const encoded=splitStorageState(source);
  const boot=await db.query('select storage_bootstrap($1,$2,$3,$4,$5) result',['2026-09-08T00:00:00Z',source,JSON.stringify(encoded.resources),JSON.stringify(encoded.wallets),JSON.stringify(encoded.history)]);
  assert.equal(boot.rows[0].result.verified,true);
  await db.query('select storage_set_maintenance(false,true)');
  const snapshot=async()=>parseStorageSnapshot((await db.query('select storage_load_snapshot() value')).rows[0].value);
  const commit=async(client,params)=>(await client.query('select storage_commit_mutation($1,$2,$3,$4,$5,$6,$7,$8,$9,$10) value',Object.values(params).map(x=>Array.isArray(x)?JSON.stringify(x):x))).rows[0].value;
  const mutation=(before,value,id,readKeys)=>buildStorageMutation({snapshot:before,value,actorKey:'teacher',requestId:id,action:'teacher.fixture',payload:{id},result:{id},readKeys});
  const initial=await snapshot();assert.deepEqual(initial.value,source);
  const sessions=await Promise.all(Array.from({length:23},connect));
  const clients=[db,...sessions];
  const writes=clients.map((_,index)=>mutation(initial,{...source,studentLife:{...source.studentLife,letters:[{id:`letter-${index}`,content:`fixture-${index}`}] }},`letter-${index}`));
  const results=await Promise.all(clients.map((client,index)=>commit(client,writes[index])));
  assert(results.every(result=>result.saved));
  assert.equal((await snapshot()).value.studentLife.letters.length,24);
  assert.equal((await commit(db,writes[0])).replayed,true);
  const reused={...writes[0],p_payload_hash:'f'.repeat(64)};
  await assert.rejects(()=>commit(db,reused),/STORAGE_REQUEST_REUSED/);
  const noResult=mutation(await snapshot(),(await snapshot()).value,'no-result');
  assert.equal((await commit(db,{...noResult,p_result:null})).saved,true);
  assert.equal((await db.query("select result from storage_receipts where request_id='no-result'")).rows[0].result,null);
  const current=await snapshot();
  const debit=(id)=>mutation(current,{...current.value,currencyBalances:{...current.value.currencyBalances,'1':20},currencyHistory:{...current.value.currencyHistory,'1':[{id,studentNumber:1,before:100,after:20,delta:-80,reason:'manual',createdAt:'2026-09-08T01:00:00Z'}]}},id);
  const debits=await Promise.all([commit(db,debit('debit-a')),commit(sessions[0],debit('debit-b'))]);
  assert.equal(debits.filter(result=>result.saved).length,1);
  assert.equal((await snapshot()).value.currencyBalances['1'],20);
  const balanceSnapshot=await snapshot();
  const before17=balanceSnapshot.value.currencyHistory['17'];
  const reward=mutation(balanceSnapshot,{...balanceSnapshot.value,currencyBalances:{...balanceSnapshot.value.currencyBalances,'17':106},currencyHistory:{...balanceSnapshot.value.currencyHistory,'17':[{id:'new-six',studentNumber:17,before:100,after:106,delta:6,reason:'weekly_mission',createdAt:'2026-09-08T01:00:00Z'},...before17]}},'new-six');
  assert.equal((await commit(db,reward)).saved,true);assert.equal((await commit(db,reward)).replayed,true);
  assert.deepEqual((await db.query('select storage_reconcile_wallets() value')).rows[0].value,[]);
  assert.deepEqual((await snapshot()).value.currencyHistory['17'][1],historical);
  // Old historical chains deliberately differ from the cutover balance. They remain evidence, never replayed money.
  assert.equal((await snapshot()).value.currencyBalances['17'],106);
  const beforeDelete=await snapshot();
  const withoutFirst={...beforeDelete.value,studentLife:{...beforeDelete.value.studentLife,letters:beforeDelete.value.studentLife.letters.filter(row=>row.id!=='letter-0')}};
  assert.equal((await commit(db,mutation(beforeDelete,withoutFirst,'remove'))).saved,true);
  const deleted=await snapshot();
  const restored={...deleted.value,studentLife:{...deleted.value.studentLife,letters:[{id:'letter-0',content:'new entity'},...deleted.value.studentLife.letters]}};
  assert.equal((await commit(db,mutation(deleted,restored,'recreate'))).saved,true);
  const stale={...beforeDelete.value,studentLife:{...beforeDelete.value.studentLife,letters:beforeDelete.value.studentLife.letters.map(row=>row.id==='letter-0'?{...row,content:'stale overwrite'}:row)}};
  assert.equal((await commit(db,mutation(beforeDelete,stale,'stale'))).saved,false);
  const libraryStart=await snapshot();
  const placed={id:'placed-book',studentNumber:1,title:'fixture',librarySlot:0,unknown:null};
  const unplaced={id:'unplaced-book',studentNumber:2,title:'fixture-unplaced'};
  const withLibrary={...libraryStart.value,libraryCompetition:{seasonId:'2026-09',participants:[1,2]},studentLife:{...libraryStart.value.studentLife,books:[placed,unplaced]}};
  assert.equal((await commit(db,mutation(libraryStart,withLibrary,'library-start'))).saved,true);
  const library=await snapshot();
  const rollover={...library.value,libraryCompetition:{...library.value.libraryCompetition,seasonId:'2026-10'},studentLife:{...library.value.studentLife,books:[unplaced]}};
  const archive={seasonId:'2026-09',archivedAt:'2026-10-01T00:00:00Z',standings:Array.from({length:17},(_,index)=>({studentNumber:index+1,score:0})),books:[placed]};
  const rolloverParams=buildStorageMutation({snapshot:library,value:rollover,actorKey:'teacher',requestId:'library-rollover',action:'libraryCompetitionRollover',payload:{month:'2026-10'},result:{saved:true},readKeys:['scope:libraryCompetition:shared','collection:/studentLife/books'],archive});
  await assert.rejects(()=>commit(db,{...rolloverParams,p_archive:{...archive,books:[]}}),/STORAGE_INVALID_MUTATION/);
  await assert.rejects(()=>commit(db,{...rolloverParams,p_archive:{...archive,books:[{...placed,unknown:'altered'}]}}),/STORAGE_INVALID_MUTATION/);
  const altered=buildStorageMutation({snapshot:library,value:{...rollover,studentLife:{...rollover.studentLife,books:[]}},actorKey:'teacher',requestId:'library-bad',action:'libraryCompetitionRollover',payload:{month:'2026-10'},result:{},readKeys:['scope:libraryCompetition:shared','collection:/studentLife/books'],archive});
  await assert.rejects(()=>commit(db,altered),/STORAGE_INVALID_MUTATION/);
  assert.equal((await commit(db,rolloverParams)).saved,true);
  assert.deepEqual((await snapshot()).value.studentLife.books,[unplaced]);
  assert.deepEqual((await db.query('select books from library_competition_archives')).rows[0].books,[placed]);
  await assert.rejects(()=>db.query("update app_settings set value=value where id='school-timer-main'"),/STORAGE_LEGACY_WRITE_DISABLED/);
  await assert.rejects(()=>db.query('delete from wallet_ledger'),/STORAGE_LEDGER_IMMUTABLE/);
  await db.query('select storage_set_maintenance(true)');
  const paused=await snapshot();await assert.rejects(()=>commit(db,mutation(paused,paused.value,'paused')),/STORAGE_MAINTENANCE/);
  await assert.rejects(()=>db.query('select storage_set_maintenance(true,false)'),/STORAGE_ROLLBACK_REQUIRES_FORWARD_RECOVERY/);
 } finally {
  await Promise.all(connections.map(client=>client.end()));
  await admin.query(`drop database ${database}`);await admin.end();
 }
});
