import assert from 'node:assert/strict';
import {readFile, writeFile} from 'node:fs/promises';
import {createHash} from 'node:crypto';
import {chromium} from '/Users/ibyeonghyeon/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright/index.mjs';
const dir=new URL('./',import.meta.url).pathname;
const phase=process.argv[2]??'before';
const hash=async()=>createHash('sha256').update(await readFile('src/components/student/library/CanvasLibraryGame.tsx')).update(await readFile('src/index.css')).digest('hex');
const result={phase,sourceStart:await hash(),screenshots:[],checks:[],errors:[],cleanup:[]};
const browser=await chromium.launch({headless:true,executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome'});
try {
 const context=await browser.newContext({viewport:{width:1280,height:800}});
 await context.route('**/*',r=>{const u=new URL(r.request().url());return u.hostname==='127.0.0.1'&&u.port==='3047'?r.continue():r.abort();});
 const page=await context.newPage();page.setDefaultTimeout(7000);page.on('pageerror',e=>result.errors.push(e.message));
 const shot=async name=>{await page.evaluate(()=>new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve))));const path=dir+phase+'-'+name+'.png';await page.screenshot({path});result.screenshots.push(path);};
 await page.goto('http://127.0.0.1:3047/.omo/evidence/library-receive-confirm/index.html');
 const canvas=page.locator('canvas');await canvas.waitFor();
 await page.waitForFunction(()=>document.querySelector('canvas')?.dataset.nearbyTarget==='registration-desk');
 assert.deepEqual(await page.evaluate(()=>[innerWidth,innerHeight]),[1280,800]);
 await canvas.focus();await page.keyboard.press('e');
 await page.getByLabel('책 제목',{exact:true}).fill('달빛 도서관');
 await page.getByLabel('글쓴이',{exact:true}).fill('고마');
 assert.equal(await page.getByLabel('쪽수',{exact:true}).count(),0);
 await page.getByLabel('한 줄 감상',{exact:true}).fill('친구를 도와주는 장면이 따뜻했어요.');
 await shot('form');await page.getByRole('button',{name:'책 받기',exact:true}).click();
 await shot('submitted');
 result.checks.push({confirmation:await page.getByRole('dialog',{name:'이 책을 받을까요?'}).count(),dialogCount:await page.getByRole('dialog').count()});
 if(phase==='after'){
  assert.equal(result.checks[0].confirmation,1);assert.equal(result.checks[0].dialogCount,1);
  const confirm=page.getByRole('dialog',{name:'이 책을 받을까요?'});
  const status=page.locator('.student-canvas-library-status');
  assert.equal((await status.textContent()).includes('운반 중'),false);
  assert.match(await confirm.textContent(),/달빛 도서관/);assert.match(await confirm.textContent(),/고마/);assert.match(await confirm.textContent(),/친구를 도와주는 장면이 따뜻했어요./);
  for(let i=0;i<6;i++){await page.keyboard.press('Tab');assert.equal(await confirm.evaluate(e=>e.contains(document.activeElement)),true);}
  await page.getByRole('button',{name:'다시 수정',exact:true}).click();
  assert.equal(await page.getByLabel('책 제목',{exact:true}).inputValue(),'달빛 도서관');
  assert.equal(await page.getByLabel('글쓴이',{exact:true}).inputValue(),'고마');
  assert.equal(await page.getByLabel('한 줄 감상',{exact:true}).inputValue(),'친구를 도와주는 장면이 따뜻했어요.');await shot('back-to-edit');
  await page.getByLabel('한 줄 감상',{exact:true}).fill('   ');await page.getByRole('button',{name:'책 받기',exact:true}).click();
  assert.equal(await confirm.count(),0);await page.getByRole('alert').waitFor();await shot('invalid');
  await page.getByLabel('한 줄 감상',{exact:true}).fill('용기를 내는 모습이 멋졌어요.');
  await page.getByLabel('한 줄 감상',{exact:true}).press('Enter');await confirm.waitFor();assert.match(await confirm.textContent(),/용기를 내는 모습이 멋졌어요./);
  await page.keyboard.press('Escape');assert.equal(await page.getByLabel('한 줄 감상',{exact:true}).inputValue(),'용기를 내는 모습이 멋졌어요.');
  await page.getByRole('button',{name:'책 받기',exact:true}).click();await page.getByRole('button',{name:'확인창 닫기',exact:true}).click();
  assert.equal(await page.getByLabel('책 제목',{exact:true}).inputValue(),'달빛 도서관');
  await page.getByRole('button',{name:'책 받기',exact:true}).click();await page.locator('.student-confirm-dialog-backdrop').click({position:{x:8,y:8}});
  assert.equal(await page.getByLabel('한 줄 감상',{exact:true}).inputValue(),'용기를 내는 모습이 멋졌어요.');
  result.checks.push('수정·Escape·X·바깥 클릭은 입력 보존; 빈 감상은 확인 진입 차단; Enter는 확인창까지만; 포커스 trap');
  await page.getByLabel('책 제목',{exact:true}).fill('가'.repeat(50));await page.getByLabel('글쓴이',{exact:true}).fill('나'.repeat(30));
  await page.getByLabel('한 줄 감상',{exact:true}).fill('다'.repeat(100));
  await page.getByRole('button',{name:'책 받기',exact:true}).click();await shot('long-text');
  await page.evaluate(()=>{document.documentElement.style.fontSize='200%';});await shot('text-zoom');
  assert.equal(await confirm.evaluate(e=>e.scrollWidth<=e.clientWidth),true);
  const box=await confirm.boundingBox();assert.ok(box&&box.x>=0&&box.y>=0&&box.x+box.width<=1280&&box.y+box.height<=800);
  result.checks.push(await page.evaluate(()=>({scrollY,scrollHeight:document.documentElement.scrollHeight,canvas:document.querySelector('canvas')?.getBoundingClientRect().toJSON()})));
  await page.getByRole('button',{name:'확인하고 받기',exact:true}).scrollIntoViewIfNeeded();await shot('text-zoom-actions');
  await page.evaluate(()=>{document.documentElement.style.fontSize='';});await page.keyboard.press('Escape');
  await page.getByLabel('책 제목',{exact:true}).fill('달빛 도서관');await page.getByLabel('글쓴이',{exact:true}).fill('고마');
  await page.getByLabel('한 줄 감상',{exact:true}).fill('용기를 내는 모습이 멋졌어요.');
  await page.getByRole('button',{name:'책 받기',exact:true}).click();await page.getByRole('button',{name:'확인하고 받기',exact:true}).click();
  await page.waitForFunction(()=>document.querySelector('.student-canvas-library-status')?.textContent?.includes('운반 중 · 달빛 도서관'));
  assert.equal(await page.getByRole('dialog').count(),0);assert.equal(await canvas.evaluate(e=>e===document.activeElement),true);await shot('received');
  result.checks.push('명시적 확인 후에만 운반, canvas 포커스 복귀; 긴 제목/글쓴이와 200% 글자 확대');
  await page.waitForFunction(()=>document.querySelector('canvas')?.dataset.action==='');
  await page.keyboard.down('ArrowLeft');await page.waitForFunction(()=>Number(document.querySelector('canvas')?.dataset.playerX)<199);await page.keyboard.up('ArrowLeft');
  await page.keyboard.down('ArrowUp');await page.waitForFunction(()=>Number(document.querySelector('canvas')?.dataset.playerY)<280);await page.keyboard.up('ArrowUp');
  await page.keyboard.down('ArrowRight');await page.waitForFunction(()=>Number(document.querySelector('canvas')?.dataset.playerX)>268);await page.keyboard.up('ArrowRight');
  result.checks.push(await canvas.evaluate(e=>({...e.dataset})));await shot('near-shelf');
  await page.keyboard.press('e');await page.getByRole('button',{name:'빈자리 51',exact:true}).click();
  await page.waitForFunction(()=>document.querySelector('canvas')?.dataset.action==='place');
  await page.waitForFunction(()=>!document.querySelector('.student-canvas-library-status')?.textContent?.includes('운반 중'));
  await page.waitForFunction(()=>document.querySelector('canvas')?.dataset.action==='');await shot('placed');
  await canvas.focus();await page.keyboard.press('e');await page.getByRole('button',{name:'달빛 도서관',exact:true}).click();
  const details=page.getByRole('dialog');assert.match(await details.textContent(),/용기를 내는 모습이 멋졌어요./);assert.doesNotMatch(await details.textContent(),/쪽수|0쪽/);await shot('reflection-details');
  result.checks.push('직접 걸어서 책 배치 후 책장 재열기 및 감상 읽기 PASS');
 }
 assert.deepEqual(result.errors,[]);await context.close();
} finally {await browser.close();result.cleanup.push('isolated Chrome closed');result.sourceEnd=await hash();await writeFile(dir+phase+'.json',JSON.stringify(result,null,2));}
console.log(JSON.stringify(result));
