begin;
update public.storage_control set active=true,maintenance=false where singleton;
insert into public.wallet_accounts(student_number,balance,opening_balance) select n,100,100 from generate_series(1,23) n;
do $$
declare first_result jsonb; repeated jsonb; current_revision text; bad boolean;
begin
 first_result:=public.classword_command_v2(2,'entry-request-001','save_entry','{"dateKey":"2099-09-08","initial":"ㄱ","word":"강아지"}',2);
 repeated:=public.classword_command_v2(2,'entry-request-001','save_entry','{"dateKey":"2099-09-08","initial":"ㄱ","word":"강아지"}',2);
 if first_result<>repeated then raise exception 'receipt replay changed'; end if;
 if (select balance from public.wallet_accounts where student_number=2)<>105 then raise exception 'duplicate payment'; end if;
 if (select count(*) from public.wallet_ledger where student_number=2)<>1 then raise exception 'duplicate ledger'; end if;
 bad:=false;
 begin perform public.classword_command_v2(2,'entry-request-001','save_entry','{"dateKey":"2099-09-08","initial":"ㄱ","word":"기린"}',2);
 exception when others then if sqlerrm<>'STORAGE_REQUEST_REUSED' then raise; end if; bad:=true; end;
 if not bad then raise exception 'request reused'; end if;
 bad:=false;
 begin perform public.classword_command_v2(4,'entry-request-002','save_entry','{"dateKey":"2099-09-08","initial":"ㄱ","word":"기린"}',2);
 exception when others then if sqlerrm<>'CLASSWORD_INITIAL_OCCUPIED' then raise; end if; bad:=true; end;
 if not bad then raise exception 'occupied slot accepted'; end if;
 bad:=false;
 begin perform public.classword_command_v2(2,'entry-request-003','save_entry',jsonb_build_object('dateKey','2099-09-08','entryId',first_result#>>'{entry,id}','initial','ㄱ','word','기린','expectedRevision','2000-01-01T00:00:00Z'),2);
 exception when others then if sqlerrm<>'CLASSWORD_ENTRY_CHANGED' then raise; end if; bad:=true; end;
 if not bad then raise exception 'stale edit accepted'; end if;
 repeated:=public.classword_command_v2(2,'entry-request-004','save_entry',jsonb_build_object('dateKey','2099-09-08','entryId',first_result#>>'{entry,id}','initial','ㄱ','word','기린','expectedRevision',first_result#>>'{entry,updated_at}'),2);
 if repeated#>>'{entry,word}'<>'기린' then raise exception 'edit failed'; end if;
 first_result:=public.classword_command_v2(2,'quiz-request-001','complete_quiz','{"dateKey":"2099-09-08","questionId":"fixture-question"}',2);
 repeated:=public.classword_command_v2(2,'quiz-request-001','complete_quiz','{"dateKey":"2099-09-08","questionId":"fixture-question"}',2);
 if first_result<>repeated then raise exception 'quiz replay changed'; end if;
 if (select count(*) from public.classword_quiz_completions where student_number=2)<>1 then raise exception 'duplicate completion'; end if;
 perform set_config('school_timer.storage_protocol','',true);
 bad:=false;
 begin insert into public.classword_entries(round_date,student_number,initial,word) values('2099-09-08',4,'ㄴ','나비');
 exception when others then if sqlerrm<>'STORAGE_LEGACY_WRITE_DISABLED' then raise; end if; bad:=true; end;
 if not bad then raise exception 'legacy write accepted'; end if;
 bad:=false;
 begin perform public.classword_command_v2(23,'entry-request-rollback','save_entry','{"dateKey":"2099-09-08","initial":"ㄴ","word":"나비"}',1);
 exception when others then if sqlerrm<>'STORAGE_PROTOCOL_REQUIRED' then raise; end if; bad:=true; end;
 if not bad then raise exception 'old protocol accepted'; end if;
 delete from public.wallet_accounts where student_number=23;
 bad:=false;
 begin perform public.classword_command_v2(23,'entry-missing-wallet','save_entry','{"dateKey":"2099-09-08","initial":"ㄴ","word":"나비"}',2);
 exception when others then if sqlerrm<>'STORAGE_WALLET_NOT_FOUND' then raise; end if; bad:=true; end;
 if not bad or exists(select 1 from public.classword_entries where student_number=23) then raise exception 'entry survived failed reward'; end if;
 if exists(select 1 from public.storage_receipts where request_id='entry-missing-wallet') then raise exception 'failed command receipt committed'; end if;
end;
$$;
rollback;
