import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import test from 'node:test';
import { getKoreanIsoWeekKey } from '../../src/lib/weeklyMission.js';
import { isQuestionRecord, parseNewspaperData, parseNewspaperQuestion } from '../../src/lib/newspaperQuestion.js';

test('실제 PostgreSQL: 질문·보상 트랜잭션, upsert, 원자적 다운로드, 요청 복구와 권한', { skip: !process.env.NEWSPAPER_PGLITE_MODULE }, async () => {
  const { PGlite } = await import(process.env.NEWSPAPER_PGLITE_MODULE!);
  const db = new PGlite();
  try {
    await db.exec('create role anon; create role authenticated; create role service_role;');
    const storage = await readFile('supabase/storage_v2.sql', 'utf8');
    await db.exec(storage.slice(0, storage.indexOf('create or replace function public.storage_set_maintenance')) + '\ncommit;');
    await db.exec(storage.slice(storage.indexOf('create or replace function public.storage_apply_wallet_delta'), storage.indexOf('create or replace function public.storage_load_snapshot')));
    await db.exec(`update public.storage_control set active=true;
      insert into public.wallet_accounts(student_number,balance,opening_balance) select n,100,100 from generate_series(1,23) n;
      create table public.weekly_mission_rewards(student_number integer,week_key text,mission_type text,reward_amount integer,source_event_id text,completed_at timestamptz,primary key(student_number,week_key,mission_type));`);
    const rewards = await readFile('supabase/storage_rewards_v2.sql', 'utf8');
    await db.exec(rewards.slice(rewards.indexOf('create or replace function public.claim_weekly_mission_reward_v2'), rewards.indexOf('create or replace function public.claim_personal_question_weekly_reward_v2')));
    const sql = await readFile('supabase/newspaper_questions.sql', 'utf8');
    await db.exec(sql);
    await db.exec(sql);
    const command = async (actor: number, value: Record<string, unknown>, id = crypto.randomUUID()): Promise<Record<string, unknown>> => {
      const response = await db.query('select public.newspaper_command($1,$2,$3) as result', [actor, id, JSON.stringify(value)]);
      const result: unknown = response.rows[0].result;
      assert.ok(isQuestionRecord(result)); return result;
    };
    const read = async (actor: number, week: string) => {
      const result = await db.query('select public.newspaper_read($1,$2) as result', [actor, week]);
      return parseNewspaperData(result.rows[0].result);
    };
    const weekKey = getKoreanIsoWeekKey();
    const submit = { action: 'submit', weekKey, questionType: 'personal', questionText: '하늘은 왜 파란가요?', expectedUpdatedAt: null };
    await assert.rejects(command(3, { ...submit, questionType: 'topic' }), /QUESTION_TOPIC_REQUIRED/);
    await command(0, { action: 'topic', weekKey, topicText: '자연', expectedUpdatedAt: null });
    let data = await read(0, weekKey);
    await assert.rejects(command(3, { ...submit, questionType: 'topic', topicRevision: data.topics[0].updated_at }), /QUESTION_PERSONAL_REQUIRED/);
    const requestId = crypto.randomUUID();
    const first = await command(3, submit, requestId);
    const replay = await command(3, submit, requestId);
    assert.deepEqual(replay, first);
    assert.equal(Reflect.get(Object(first.reward), 'balance'), 115);
    await assert.rejects(command(3, { ...submit, questionText: '바다는 왜 파란가요?' }, requestId), /QUESTION_REQUEST_REUSED/);
    const row = parseNewspaperQuestion(first.question);
    await command(3, { ...submit, questionType: 'topic', topicRevision: data.topics[0].updated_at });
    await command(4, submit);
    const downloads = await Promise.all([command(0, { action: 'download', weekKey, mode: 'all', cumulative: true }), command(0, { action: 'download', weekKey, mode: 'all', cumulative: true })]);
    const sets = downloads.map(result => { assert.ok(Array.isArray(result.questions)); return result.questions.map(parseNewspaperQuestion); });
    assert.equal(sets[0].length + sets[1].length, 3);
    assert.equal(new Set(sets.flat().map(row => row.id)).size, 3);
    const downloaded = await read(0, weekKey);
    const full = await command(0, { action: 'download', weekKey, mode: 'all', cumulative: false });
    assert.ok(Array.isArray(full.questions)); assert.equal(full.questions.length, 3);
    assert.deepEqual((await read(0, weekKey)).questions.map(row => row.downloaded_at), downloaded.questions.map(row => row.downloaded_at));
    const edited = await command(3, { ...submit, questionText: '바다는 왜 파란가요?', expectedUpdatedAt: row.updated_at });
    const changed = parseNewspaperQuestion(edited.question);
    assert.equal(changed.id, row.id); assert.equal(changed.created_at, row.created_at); assert.equal(changed.downloaded_at, null);
    assert.equal(Reflect.get(Object(edited.reward), 'awarded'), false);
    assert.equal((await db.query('select balance from public.wallet_accounts where student_number=3')).rows[0].balance, 115);
    await assert.rejects(command(3, { ...submit, expectedUpdatedAt: row.updated_at }), /QUESTION_CONFLICT/);
    await assert.rejects(command(3, { action: 'delete', id: row.id, expectedUpdatedAt: changed.updated_at }), /QUESTION_FORBIDDEN/);
    await command(0, { action: 'topic', weekKey, topicText: '바다', expectedUpdatedAt: data.topics[0].updated_at });
    data = await read(0, weekKey); assert.equal(data.topics.length, 1); assert.equal(data.topics[0].topic_text, '바다');
    const student = await read(3, weekKey); assert.equal(student.history.length, 2); assert.ok(student.history.every(row => row.student_number === 3)); assert.ok(student.questions.every(row => row.downloaded_at === null));
    const retryDownloadId = crypto.randomUUID();
    const downloadCommand = { action: 'download', weekKey, mode: 'personal', cumulative: true };
    const claimed = await command(0, downloadCommand, retryDownloadId);
    assert.deepEqual(await command(0, downloadCommand, retryDownloadId), claimed);
    await command(0, { action: 'delete', id: row.id, expectedUpdatedAt: changed.updated_at });
    assert.equal((await read(0, weekKey)).questions.length, 2);
    await assert.rejects(command(3, submit, requestId), /QUESTION_REQUEST_REUSED/);
    await assert.rejects(command(0, downloadCommand, retryDownloadId), /QUESTION_REQUEST_REUSED/);
    await assert.rejects(command(0, { action: 'reset', confirmation: '취소' }), /QUESTION_FORBIDDEN/);
    await command(0, { action: 'reset', confirmation: '모든 기록 초기화' });
    const reset = await read(0, weekKey); assert.equal(reset.questions.length, 0); assert.equal(reset.topics.length, 0);
    await assert.rejects(command(3, submit, requestId), /QUESTION_REQUEST_REUSED/);
    assert.equal((await db.query('select balance from public.wallet_accounts where student_number=3')).rows[0].balance, 115);
    assert.ok((await db.query("select count(*)::integer as n from public.newspaper_audit where action='reset'")).rows[0].n > 0);
    await db.exec('set role anon');
    await assert.rejects(db.query('select * from public.newspaper_questions'), /permission denied/);
    await assert.rejects(db.query('select public.newspaper_read(0,$1)', [weekKey]), /permission denied/);
  } finally { await db.close(); }
});
