import assert from 'node:assert/strict';
import { chromium } from '/Users/ibyeonghyeon/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright/index.mjs';
const browser = await chromium.launch({ headless: true, executablePath: '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome' });
try {
  const page = await browser.newPage({ viewport: { width: 1280, height: 800 } });
  const errors = [];
  page.on('pageerror', error => errors.push(error.message));
  await page.goto('http://127.0.0.1:3044/.omo/evidence/library-competition/game-fixture.html');
  const canvas = page.getByRole('application');
  await canvas.waitFor();
  await page.waitForFunction(() => document.querySelector('canvas')?.dataset.playerX);
  assert.deepEqual(await page.evaluate(() => [innerWidth, innerHeight]), [1280, 800]);
  await canvas.focus();
  await page.keyboard.press('e');
  await page.getByRole('textbox', { name: '책 제목', exact: true }).fill('다음 달에도 남는 초안');
  await page.getByRole('textbox', { name: '글쓴이', exact: true }).fill('합성 작가');
  await page.getByRole('textbox', { name: '쪽수', exact: true }).fill('123');
  await page.evaluate(() => window.dispatchEvent(new Event('qa-season-change')));
  await page.getByRole('dialog').waitFor({ state: 'hidden' });
  await canvas.focus();
  await page.keyboard.press('e');
  assert.equal(await page.getByRole('textbox', { name: '책 제목', exact: true }).inputValue(), '다음 달에도 남는 초안');
  assert.equal(await page.getByRole('textbox', { name: '글쓴이', exact: true }).inputValue(), '합성 작가');
  assert.equal(await page.getByRole('textbox', { name: '쪽수', exact: true }).inputValue(), '123');
  await page.getByRole('button', { name: '책 받기', exact: true }).click();
  await page.getByRole('dialog').waitFor({ state: 'hidden' });
  await page.waitForFunction(() => !document.querySelector('canvas')?.dataset.action);
  await canvas.focus();
  await page.keyboard.down('ArrowLeft');
  await page.waitForFunction(() => Number(document.querySelector('canvas')?.dataset.playerX) <= 108);
  await page.keyboard.up('ArrowLeft');
  await page.waitForFunction(() => document.querySelector('canvas')?.dataset.nearbyTarget === 'competition-board' || document.querySelector('canvas')?.dataset.target === 'competition-board');
  await page.screenshot({ path: '.omo/evidence/library-competition/game-board-near.png' });
  for (const key of ['e', 'ㄷ', 'Enter']) {
    await canvas.focus();
    if (key === 'ㄷ') await canvas.dispatchEvent('keydown', { key: 'ㄷ', code: 'KeyE', bubbles: true });
    else await page.keyboard.press(key);
    await page.getByRole('dialog', { name: '순위판 연결 확인' }).waitFor();
    await page.getByRole('button', { name: '닫기', exact: true }).click();
  }
  const box = await canvas.boundingBox();
  assert.ok(box);
  await canvas.click({ position: { x: 106 / 624 * box.width, y: 281 / 376 * box.height } });
  await page.getByRole('dialog', { name: '순위판 연결 확인' }).waitFor();
  await page.getByRole('button', { name: '닫기', exact: true }).click();
  await canvas.focus();
  await page.keyboard.down('ArrowRight');
  await page.waitForFunction(() => Number(document.querySelector('canvas')?.dataset.playerX) >= 170);
  await page.keyboard.up('ArrowRight');
  await page.keyboard.down('ArrowUp');
  await page.waitForFunction(() => Number(document.querySelector('canvas')?.dataset.playerY) <= 278);
  await page.keyboard.up('ArrowUp');
  await page.keyboard.down('ArrowRight');
  await page.waitForFunction(() => Number(document.querySelector('canvas')?.dataset.playerX) >= 270);
  await page.keyboard.up('ArrowRight');
  await page.keyboard.press('e');
  await page.getByRole('dialog').waitFor();
  await page.evaluate(() => window.dispatchEvent(new Event('qa-season-change')));
  await page.getByRole('dialog').waitFor({ state: 'hidden' });
  assert.ok(await page.locator('.student-canvas-library-status').innerText());
  await canvas.focus();
  await page.keyboard.press('e');
  await page.getByRole('dialog').waitFor();
  const emptySlot = page.locator('.student-canvas-library-slot-grid .is-empty').first();
  await emptySlot.click();
  await page.getByRole('dialog').waitFor({ state: 'hidden' });
  assert.equal(await page.locator('.student-canvas-library-status').count(), 0);
  await page.waitForFunction(() => !document.querySelector('canvas')?.dataset.action);
  await page.screenshot({ path: '.omo/evidence/library-competition/game-season-draft-placed.png' });
  assert.deepEqual(errors, []);
  console.log(JSON.stringify({ passed: true, viewport: [1280, 800], checks: ['registration fields survive rollover', 'walked from entrance to board', 'E / ㄷ / Enter / canvas click', 'slot modal closes on rollover', 'carried draft placed successfully after rollover'], cleanup: 'isolated browser closed in finally; root-owned server retained' }));
} finally { await browser.close(); }
