import assert from 'node:assert/strict';
import { readFile, writeFile } from 'node:fs/promises';
import { createHash } from 'node:crypto';
import { chromium } from '/Users/ibyeonghyeon/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright/index.mjs';

const dir = new URL('./', import.meta.url).pathname;
const root = new URL('../../../', import.meta.url).pathname;
const qaPort = process.env.CANVAS_QA_PORT || '3023';
const qaPrefix = process.env.CANVAS_QA_PREFIX || 'root';
const receipt = { generatedAt: new Date().toISOString(), checks: {}, screenshots: [], blockedRequests: [], errors: [], cleanup: [] };
const sourceFiles = ['src/lib/canvasLibraryWorld.ts', 'src/lib/useModalFocus.ts', 'src/components/student/library/CanvasLibraryGame.tsx', 'src/components/student/library/CanvasLibraryRenderer.ts', 'src/components/student/library/CanvasLibraryPalette.ts', 'src/index.css', '.omo/evidence/canvas-library/play.tsx'];
const sourceHashes = async () => Object.fromEntries(await Promise.all(sourceFiles.map(async file => [file, createHash('sha256').update(await readFile(root + file)).digest('hex')])));
const initialSourceHashes = await sourceHashes();
const browser = await chromium.launch({ headless: true, executablePath: '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome' });
try {
  const context = await browser.newContext({ viewport: { width: 1280, height: 800 }, deviceScaleFactor: 1 });
  await context.route('**/*', async route => {
    const url = new URL(route.request().url());
    if (url.hostname !== '127.0.0.1' || url.port !== qaPort || url.pathname.startsWith('/api')) {
      receipt.blockedRequests.push({ origin: url.origin, api: url.pathname.startsWith('/api') });
      return route.abort();
    }
    return route.continue();
  });
  const page = await context.newPage();
  page.on('pageerror', error => receipt.errors.push(error.message));
  await page.goto(`http://127.0.0.1:${qaPort}/.omo/evidence/canvas-library/play.html`);
  const canvas = page.getByRole('application');
  await canvas.waitFor();
  await page.waitForTimeout(150);
  const position = () => canvas.evaluate(el => ({ x: Number(el.dataset.playerX), y: Number(el.dataset.playerY), target: el.dataset.nearbyTarget }));
  const shot = async name => {
    const path = `${dir}${qaPrefix}-${name}.png`;
    await page.screenshot({ path });
    const png = await readFile(path);
    assert.equal(png.subarray(0, 8).toString('hex'), '89504e470d0a1a0a');
    assert.deepEqual([png.readUInt32BE(16), png.readUInt32BE(20)], [1280, 800]);
    receipt.screenshots.push(path);
  };
  const walkAxis = async (axis, value) => {
    for (let n = 0; n < 50; n++) {
      const before = await position();
      const delta = value - before[axis];
      if (Math.abs(delta) < 3) return;
      const key = axis === 'x' ? (delta > 0 ? 'd' : 'a') : (delta > 0 ? 's' : 'w');
      await page.keyboard.down(key);
      await page.waitForTimeout(Math.min(150, Math.max(20, Math.abs(delta) * 10)));
      await page.keyboard.up(key);
      if (n > 4 && Math.abs((await position())[axis] - before[axis]) < .1) throw new Error(`Collision blocked ${axis} toward ${value} at ${JSON.stringify(before)}`);
    }
    throw new Error(`Could not reach ${axis}=${value}`);
  };
  receipt.checks.viewport = await page.evaluate(() => ({ width: innerWidth, height: innerHeight, overflowX: document.documentElement.scrollWidth-innerWidth, overflowY: document.documentElement.scrollHeight-innerHeight }));
  assert.deepEqual(receipt.checks.viewport, { width: 1280, height: 800, overflowX: 0, overflowY: 0 });
  await shot('empty');
  await canvas.focus();
  await page.keyboard.down('a');
  await page.waitForTimeout(100);
  await shot('walk-mid');
  await page.keyboard.up('a');
  await page.waitForTimeout(100);
  await shot('walk-settled');
  await walkAxis('x', 109);
  await walkAxis('y', 304);
  assert.equal((await position()).target, 'registration-desk');
  receipt.checks.deskApproach = await position();
  await page.keyboard.press('e');
  await page.getByRole('dialog').waitFor();
  await shot('registration');
  const frozen = await position();
  await page.getByRole('textbox', { name: '책 제목', exact: true }).fill('달빛 우체국');
  await page.getByRole('textbox', { name: '글쓴이', exact: true }).fill('김별');
  await page.getByRole('textbox', { name: '쪽수', exact: true }).fill('0');
  await page.getByRole('button', { name: '책 받기', exact: true }).click();
  assert.match(await page.getByRole('alert').innerText(), /1~5000/);
  assert.deepEqual(await position(), frozen);
  receipt.checks.invalidAndModalFreeze = true;
  await shot('invalid');
  await page.getByRole('textbox', { name: '쪽수', exact: true }).fill('80');
  await page.getByRole('button', { name: '책 받기', exact: true }).click();
  await page.getByRole('dialog').waitFor({ state: 'hidden' });
  assert.equal(await canvas.evaluate(el => document.activeElement === el), true);
  await shot('carry');
  await walkAxis('x', 266);
  await walkAxis('y', 122);
  await page.keyboard.press('e');
  await page.getByRole('button', { name: '빈자리 1', exact: true }).waitFor();
  await page.waitForFunction(() => document.activeElement?.getAttribute('aria-label') === '빈자리 1');
  await page.keyboard.press('ArrowDown');
  assert.equal(await page.getByRole('button', { name: '빈자리 7', exact: true }).evaluate(el => document.activeElement === el), true, 'ArrowDown must focus slot7');
  for (let n = 0; n < 8; n++) {
    await page.keyboard.press('Tab');
    assert.equal(await page.getByRole('dialog').evaluate(el => el.contains(document.activeElement)), true, `Tab ${n} escaped slot dialog`);
  }
  receipt.checks.slotKeyboardAndFocusTrap = true;
  await shot('slots');
  await page.keyboard.press('Escape');
  await page.keyboard.press('e');
  await page.getByRole('button', { name: '빈자리 1', exact: true }).click();
  await page.getByRole('dialog').waitFor({ state: 'hidden' });
  await shot('placement-start');
  await page.waitForTimeout(100);
  await shot('placement-mid');
  await page.waitForTimeout(500);
  await shot('placed');
  await walkAxis('x', 200);
  await page.keyboard.press('e');
  assert.match(await page.getByRole('dialog').innerText(), /달빛 우체국/);
  assert.match(await page.getByRole('dialog').innerText(), /김별/);
  await shot('details');
  await page.keyboard.press('Escape');
  receipt.checks.actualBookLoop = true;
  await walkAxis('y', 304);
  await walkAxis('x', 109);
  await page.getByRole('button', { name: '가까운 곳 살펴보기: 책 등록', exact: true }).click();
  const longTitle = '도서관'.repeat(16) + '책';
  const literalAuthor = '<img src=x onerror=alert(1)>';
  await page.getByRole('textbox', { name: '책 제목', exact: true }).fill(longTitle);
  await page.getByRole('textbox', { name: '글쓴이', exact: true }).fill(literalAuthor);
  await page.getByRole('textbox', { name: '쪽수', exact: true }).fill('5000');
  await page.getByRole('button', { name: '책 받기', exact: true }).click();
  await page.getByRole('dialog').waitFor({ state: 'hidden' });
  await walkAxis('x', 200);
  await walkAxis('y', 122);
  assert.equal((await position()).target, 'placed-book:0');
  await shot('carrying-near-placed');
  await canvas.click({ position: { x: 532, y: 146 } });
  await page.getByRole('heading', { name: '책을 둘 자리', exact: true }).waitFor();
  receipt.checks.inRangeCanvasShelfClick = true;
  await page.getByRole('button', { name: '빈자리 2', exact: true }).click();
  await page.getByRole('dialog').waitFor({ state: 'hidden' });
  await walkAxis('x', 225);
  await page.keyboard.press('e');
  assert.match(await page.getByRole('dialog').innerText(), /도서관/);
  assert.equal(await page.getByRole('dialog').locator('img').count(), 0);
  assert.equal(await page.getByRole('dialog').getByText(literalAuthor, { exact: true }).count(), 1);
  receipt.checks.pointerDeskAndSecondBook = true;
  receipt.checks.untrustedTextIsLiteral = true;
  await shot('long-details');
  await page.addStyleTag({ content: 'html { font-size: 200% !important; }' });
  await shot('text-200');
  const enlargedReturn = page.getByRole('button', { name: '도서관으로', exact: true });
  await enlargedReturn.scrollIntoViewIfNeeded();
  const returnBounds = await enlargedReturn.boundingBox();
  assert.ok(returnBounds && returnBounds.y >= 0 && returnBounds.y + returnBounds.height <= 800);
  await shot('text-200-actions');
  assert.equal(await page.evaluate(() => document.documentElement.scrollHeight-innerHeight), 0);
  const enlargedClose = page.getByRole('button', { name: '책 정보 닫기', exact: true });
  await enlargedClose.scrollIntoViewIfNeeded();
  await enlargedClose.click();
  assert.equal(await page.getByRole('dialog').count(), 0);
  receipt.checks.text200CloseReachable = true;
  await page.addStyleTag({ content: 'html { font-size: 100% !important; }' });
  const cdp = await context.newCDPSession(page);
  await cdp.send('Emulation.setFocusEmulationEnabled', { enabled: false });
  const other = await context.newPage();
  const otherCdp = await context.newCDPSession(other);
  await otherCdp.send('Emulation.setFocusEmulationEnabled', { enabled: false });
  await page.bringToFront();
  await canvas.focus();
  await page.keyboard.down('d');
  await page.waitForTimeout(120);
  await other.bringToFront();
  await page.waitForTimeout(120);
  assert.equal(await page.evaluate(() => document.hasFocus()), false);
  const blurred = await position();
  await page.waitForTimeout(220);
  assert.deepEqual(await position(), blurred);
  await page.bringToFront();
  await page.waitForTimeout(220);
  assert.deepEqual(await position(), blurred);
  await page.keyboard.up('d');
  receipt.checks.realBlurAndResume = { stopped: blurred, noStuckKey: true };
  await other.close();
  await page.emulateMedia({ reducedMotion: 'reduce' });
  const beforeReduced = await position();
  await canvas.focus();
  await page.keyboard.down('a');
  await page.waitForTimeout(100);
  await shot('reduced-motion');
  await page.keyboard.up('a');
  assert.ok((await position()).x < beforeReduced.x);
  assert.equal(await page.evaluate(() => matchMedia('(prefers-reduced-motion: reduce)').matches), true);
  receipt.checks.reducedMotionStillPlayable = true;
  assert.deepEqual(receipt.errors, []);
  receipt.sourceSha256 = await sourceHashes();
  assert.deepEqual(receipt.sourceSha256, initialSourceHashes, 'Source changed during run; recapture against stable source');
  receipt.passed = true;
} catch (error) {
  receipt.passed = false;
  receipt.failure = String(error);
  receipt.failureStack = error.stack;
  process.exitCode = 1;
} finally {
  await browser.close();
  receipt.cleanup.push(`Owned isolated Chrome browser and contexts closed; root Vite${qaPort} remains registered for ongoing QA.`);
  await writeFile(`${dir}${qaPrefix}-play-qa.json`, JSON.stringify(receipt, null, 2));
  console.log(JSON.stringify(receipt, null, 2));
}
